# AP = Atlas Prompt
AP = {    
    'blocks': [
        "Wake up from a long nap.",
        "Give self a good stretch.",
        "Groom self with tongue.",
        "Have a good scratch.",
        "Yawn.",
        "Blink.",
        "Look around the room.",
        "Listen for any noises.",
        "Smell anything new in the room.",
        "Get up on hind legs and look out the window.",
        "Sit in the sunbeam.",
        "Play with a toy.",
        "Climb furniture.",
        "Get into hammock.",
        "Get a drink of water.",
        "Use the litter box.",
        "Lay in a sunny spot.",
        "Watch birds at the feeder.",
        "Chase a bug.",
        "Sleep some more.",
        "Drink water from a bowl.",
        "Eat wet food.",
        "Eat dry food.",
        "Sleep in a comfortable place.",
        "Scratch furniture.",
        "Hunt for rodents and birds.",
        "Stalk prey.",
        "Drink milk.",
        "Shed fur.",
        "Chirp.",
        "Meow.",
        "Sing.",
        "Show affection.",
        "Be territorial.",
        "Be lazy.",
        "Sleep a lot.",
        "Be curious.",
        "Cause mischief.",
        "Is the best.",
        "Ponder reality.",
        "Climb on things.",
        "Jump on people.",
        "Steal things.",
        "Hide things.",
        "Get into things.",
        "Knock things over.",
        "Break things.",
        "Make noise.",
        "Run around.",
        "Get into places.",
        "Be lazy.",
        "Eat a lot.",
        "Be independent.",
        "Guard against chipmunks.",
        "Brace for garbage pickup.",
        "Investigate a smell.",
        "Eat fuzz.",
        "Play with string.",
        "Chase a spring.",
        "Take down the mini dragons.",
        "Survey territory.",
        "Bite piano keys.",
        "Run through the tunnel.",
        "Act vicious.",
        "Is sweet.",
        "Find the humans.",
        "Bat at the blinds."
    ],
    "form": [
        "acrostic",
        "ballad",
        "dramatic monologue",
        "elegy",
        "free verse",
        "haiku",
        "limerick",
        "ode",
        "sapphic",
        "sonnet",
        "villanelle",
    ],
    "wake": [
        "wakes up to the sound of an alarm clock",
        "wakes up to the sound of birds outside the window",
        "wakes up to the sound of mother calling for breakfast",
        "wakes up to the sound of father snoring",
        "wakes up to the sound of traffic outside",
        "wakes up to the sound of a dog barking",
        "wakes up to the sound of a cat meowing",
        "wakes up to the sound of music playing",
        "wakes up to the sound of someone cooking in the kitchen",
        "wakes up to the sound of silence"
    ],
    "dream": [
        "to fly",
        "to be rich",
        "to travel the world",
        "to be famous",
        "to be loved",
        "to be happy",
        "to be healthy",
        "to help others",
        "to make a difference",
        "to be a better person",
        "a nightmare, but it is gone and no bother"
    ],
    "sleep": [
        "feels like he could fall asleep standing up",
        "can't keep his eyes open",
        "has the zoomies",
        "needs food",
        "is ready for a nap",
        "is sleepy",
        "wants to snuggle",
        "is getting into trouble",
        "is looking out the window",
        "knows the chipmunks are up to something"
    ],
    "activity": [
        "sleeping",
        "eating",
        "drinking",
        "grooming",
        "stretching",
        "scratching",
        "vocalizing",
        "kneading",
        "exploring"
    ],
    "mood": [
        "agitated", 
        "annoyed",
        "anxious",
        "bored", 
        "calm", 
        "cheerful", 
        "confident", 
        "contemplative", 
        "depressed", 
        "disappointed", 
        "disgusted", 
        "embarrassed", 
        "excited", 
        "frustrated", 
        "gleeful", 
        "guilty", 
        "happy", 
        "hopeful", 
        "jealous", 
        "lonely", 
        "loving", 
        "mad", 
        "nostalgic", 
        "proud", 
        "relaxed", 
        "sad", 
        "sentimental", 
        "stressed", 
        "surprised", 
        "thankful", 
        "uneasy", 
        "worried"
    ],
    "food": [
        "chicken",
        "turkey",
        "beef",
        "pork",
        "lamb",
        "venison",
        "rabbit",
        "duck",
        "goose",
        "tuna"
    ],
    "action": [
        "pounce",
        "stalk",
        "consult",
        "check on",
        "see",
        "advise",
        "find"
    ],
    "friend": [
        "Pyxis",
        "Ru",
        "Sephora",
        "Mysterious Neighbor Cat",
        "Chipmunk",
        "Emilie",
        "David"
    ],
    "adjective": [
        "loud",
        "intelligent",
        "talented",
        "fast",
        "gullible",
        "forlorn",
        "witty",
        "nimble",
        "funny",
        "long-winded",
        "smooth",
        "sexy",
        "silly",
        "enchanting"
    ],
    "noun": [
        "dragon",
        "horse",
        "human",
        "snake",
        "lizard",
        "cat",
        "dog",
        "chipmunk",
        "cardboard box",
        "vegetable",
        "friend",
        "enemy",
        "story",
        "novel",
        "spell",
        "ride",
        "bet",
        "prophecy",
        "adventure",
        "aroma",
        "flavor",
        "mystery"
    ]
}